// Audio Step - Voice selection with ElevenLabs + AI Music
// ═══════════════════════════════════════════════════════════════════════════

import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { GlassPanel } from "../shared/GlassPanel";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { 
  Mic, 
  Music, 
  Volume2,
  Play,
  Pause,
  Check,
  Headphones,
  AudioWaveform,
  AlertCircle,
  Sparkles,
  Upload,
  X,
  RefreshCw
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { StoryScene, StoryTemplate, MusicStyle } from "../types";
import { useState, useRef, useEffect } from "react";
import { ELEVENLABS_VOICES, getVoicesByLanguage } from "@/constants/elevenlabs-voices";
import { useWorkspace } from "@/contexts/workspace-context";

interface AudioStepProps {
  template: StoryTemplate;
  scenes: StoryScene[];
  projectFolder: string; // Full folder name with timestamp for file storage
  selectedVoice: string;
  musicStyle: MusicStyle;
  backgroundMusic: string; // Legacy
  customMusicUrl: string; // User-uploaded custom music
  customMusicDuration: number; // Duration in seconds
  voiceVolume: number;
  musicVolume: number;
  duration: number; // Total video duration
  isGenerating: boolean;
  voiceoverEnabled: boolean;
  onVoiceChange: (voice: string) => void;
  onMusicStyleChange: (style: MusicStyle) => void;
  onMusicChange: (music: string) => void; // Legacy
  onCustomMusicChange: (url: string, duration: number) => void;
  onClearCustomMusic: () => void;
  onVoiceVolumeChange: (volume: number) => void;
  onMusicVolumeChange: (volume: number) => void;
  onGenerateVoiceover?: () => void;
  accentColor?: string;
}

// AI Music Styles - Generated by ElevenLabs Music API during export
const MUSIC_STYLES: Array<{
  id: MusicStyle;
  name: string;
  desc: string;
  icon: string;
  gradient: string;
}> = [
  { id: 'none', name: 'No Music', desc: 'Voice only', icon: '🔇', gradient: 'from-gray-500/20 to-gray-600/20' },
  { id: 'cinematic', name: 'Cinematic Epic', desc: 'Dramatic, powerful', icon: '🎬', gradient: 'from-purple-500/20 to-indigo-600/20' },
  { id: 'upbeat', name: 'Upbeat Happy', desc: 'Energetic, positive', icon: '😊', gradient: 'from-yellow-500/20 to-orange-500/20' },
  { id: 'calm', name: 'Calm Ambient', desc: 'Peaceful, relaxing', icon: '😌', gradient: 'from-teal-500/20 to-cyan-500/20' },
  { id: 'corporate', name: 'Corporate', desc: 'Professional, clean', icon: '💼', gradient: 'from-blue-500/20 to-sky-500/20' },
  { id: 'electronic', name: 'Electronic', desc: 'Modern, tech vibes', icon: '🎸', gradient: 'from-pink-500/20 to-rose-500/20' },
  { id: 'emotional', name: 'Emotional', desc: 'Touching, heartfelt', icon: '❤️', gradient: 'from-red-500/20 to-pink-500/20' },
  { id: 'inspiring', name: 'Inspiring', desc: 'Motivational, uplifting', icon: '🔥', gradient: 'from-amber-500/20 to-orange-600/20' },
];

export function AudioStep({
  template,
  scenes,
  projectFolder,
  selectedVoice,
  musicStyle,
  backgroundMusic,
  customMusicUrl,
  customMusicDuration,
  voiceVolume,
  musicVolume,
  duration,
  isGenerating,
  voiceoverEnabled,
  onVoiceChange,
  onMusicStyleChange,
  onMusicChange,
  onCustomMusicChange,
  onClearCustomMusic,
  onVoiceVolumeChange,
  onMusicVolumeChange,
  onGenerateVoiceover,
  accentColor = "primary",
}: AudioStepProps) {
  const { toast } = useToast();
  const { currentWorkspace } = useWorkspace();
  const [activeTab, setActiveTab] = useState<'ar' | 'en'>('ar');
  const [playingVoice, setPlayingVoice] = useState<string | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  
  // Custom music upload states
  const musicInputRef = useRef<HTMLInputElement>(null);
  const musicPreviewRef = useRef<HTMLAudioElement>(null);
  const [isUploadingMusic, setIsUploadingMusic] = useState(false);
  const [isMusicPlaying, setIsMusicPlaying] = useState(false);

  // Format duration as MM:SS
  const formatDuration = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // Get audio duration from file
  const getAudioDuration = (file: File): Promise<number> => {
    return new Promise((resolve, reject) => {
      const audio = new Audio();
      audio.onloadedmetadata = () => {
        resolve(audio.duration);
        URL.revokeObjectURL(audio.src);
      };
      audio.onerror = () => {
        reject(new Error('Could not load audio'));
        URL.revokeObjectURL(audio.src);
      };
      audio.src = URL.createObjectURL(file);
    });
  };

  // Handle custom music upload
  const handleMusicUpload = async (file: File) => {
    // Validate file type
    const validTypes = ['audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/x-wav', 'audio/m4a', 'audio/x-m4a', 'audio/ogg'];
    if (!validTypes.some(type => file.type.includes(type.split('/')[1])) && !file.name.match(/\.(mp3|wav|m4a|ogg)$/i)) {
      toast({
        title: "Invalid file type",
        description: "Please upload an audio file (MP3, WAV, M4A, OGG)",
        variant: "destructive",
      });
      return;
    }

    // Max 50MB
    if (file.size > 50 * 1024 * 1024) {
      toast({
        title: "File too large",
        description: "Please upload an audio file smaller than 50MB",
        variant: "destructive",
      });
      return;
    }

    // Check duration (max 5 minutes)
    try {
      const audioDuration = await getAudioDuration(file);
      if (audioDuration > 300) {
        toast({
          title: "Audio too long",
          description: "Maximum duration is 5 minutes. Your file is " + formatDuration(audioDuration),
          variant: "destructive",
        });
        return;
      }

      setIsUploadingMusic(true);
      const formData = new FormData();
      formData.append('file', file);
      formData.append('workspaceId', currentWorkspace?.id || 'default');
      formData.append('projectName', projectFolder); // Use projectFolder (with timestamp) for consistent storage

      const response = await fetch(`/api/${template.id}/custom-music/upload`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        throw new Error('Upload failed');
      }

      const data = await response.json();
      onCustomMusicChange(data.url, data.duration);
      
      toast({
        title: "Music uploaded",
        description: `${file.name} (${formatDuration(data.duration)}) ready to use`,
      });
    } catch (error) {
      console.error('Music upload error:', error);
      toast({
        title: "Upload failed",
        description: "Could not upload custom music",
        variant: "destructive",
      });
    } finally {
      setIsUploadingMusic(false);
    }
  };

  // Handle remove custom music
  const handleRemoveCustomMusic = () => {
    if (musicPreviewRef.current) {
      musicPreviewRef.current.pause();
      setIsMusicPlaying(false);
    }
    onClearCustomMusic();
    if (musicInputRef.current) {
      musicInputRef.current.value = '';
    }
  };

  // Toggle music preview playback
  const toggleMusicPreview = () => {
    if (!musicPreviewRef.current) return;
    
    if (isMusicPlaying) {
      musicPreviewRef.current.pause();
      setIsMusicPlaying(false);
    } else {
      musicPreviewRef.current.play();
      setIsMusicPlaying(true);
    }
  };

  // Handle audio ended
  const handleMusicEnded = () => {
    setIsMusicPlaying(false);
  };

  // Calculate total narration and word count (only if voiceover enabled)
  const totalNarration = voiceoverEnabled 
    ? scenes.map(s => s.narration).join(' ')
    : '';
  const wordCount = voiceoverEnabled 
    ? totalNarration.split(/\s+/).filter(w => w.length > 0).length
    : 0;

  const arabicVoices = getVoicesByLanguage('ar');
  const englishVoices = getVoicesByLanguage('en');
  const currentVoices = activeTab === 'ar' ? arabicVoices : englishVoices;

  // Cleanup audio on unmount
  useEffect(() => {
    return () => {
      if (audioRef.current) {
        audioRef.current.pause();
        audioRef.current = null;
      }
    };
  }, []);

  // Function to play voice preview
  const playPreview = (voiceId: string, previewUrl: string, e: React.MouseEvent) => {
    e.stopPropagation();
    
    if (playingVoice === voiceId) {
      // Stop current playing audio
      audioRef.current?.pause();
      setPlayingVoice(null);
      audioRef.current = null;
    } else {
      // Stop any currently playing audio
      if (audioRef.current) {
        audioRef.current.pause();
      }
      
      // Play new audio
      audioRef.current = new Audio(previewUrl);
      audioRef.current.play().catch(err => {
        console.error('Failed to play audio:', err);
        setPlayingVoice(null);
      });
      setPlayingVoice(voiceId);
      
      // Auto-stop when finished
      audioRef.current.onended = () => {
        setPlayingVoice(null);
      };
    }
  };

  return (
    <div className="space-y-6">
      {/* Voice Selection Section - Only if voiceoverEnabled */}
      {voiceoverEnabled && (
        <GlassPanel>
          <div className="space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className={cn(
                  "w-10 h-10 rounded-xl flex items-center justify-center",
                  "bg-gradient-to-br from-purple-500/20 to-pink-500/20"
                )}>
                  <Mic className="w-5 h-5 text-purple-400" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-white">Voice Selection</h3>
                  <p className="text-sm text-white/60">Choose a voice for your narration</p>
                </div>
              </div>

              {/* Language Tabs */}
              <div className="flex gap-2 bg-white/5 rounded-lg p-1">
                <button
                  onClick={() => setActiveTab('ar')}
                  className={cn(
                    "px-4 py-2 rounded-md text-sm font-medium transition-all",
                    activeTab === 'ar'
                      ? "bg-white/10 text-white"
                      : "text-white/60 hover:text-white/80"
                  )}
                >
                  العربية
                </button>
                <button
                  onClick={() => setActiveTab('en')}
                  className={cn(
                    "px-4 py-2 rounded-md text-sm font-medium transition-all",
                    activeTab === 'en'
                      ? "bg-white/10 text-white"
                      : "text-white/60 hover:text-white/80"
                  )}
                >
                  English
                </button>
              </div>
            </div>

            {/* Voice Grid - 2x3 layout for 6 voices */}
            <div className="grid grid-cols-2 lg:grid-cols-3 gap-3">
              <AnimatePresence mode="wait">
                {currentVoices.map((voice, index) => {
                  const isSelected = selectedVoice === voice.id;
                  const isPlaying = playingVoice === voice.id;

                  return (
                    <motion.div
                      key={`${voice.id}-${activeTab}`}
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.95 }}
                      transition={{ delay: index * 0.05 }}
                      className={cn(
                        "relative rounded-xl transition-all overflow-hidden group cursor-pointer",
                        "border backdrop-blur-sm",
                        isSelected
                          ? "border-purple-500/60 bg-gradient-to-br from-purple-500/20 to-pink-500/20 shadow-lg shadow-purple-500/20"
                          : "border-white/10 bg-white/[0.03] hover:border-purple-500/30 hover:bg-white/[0.06]"
                      )}
                      onClick={() => onVoiceChange(voice.id)}
                    >
                      {/* Selected Indicator */}
                      {isSelected && (
                        <motion.div 
                          initial={{ scale: 0 }}
                          animate={{ scale: 1 }}
                          className="absolute top-2.5 right-2.5 z-10"
                        >
                          <div className="w-6 h-6 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center shadow-lg">
                            <Check className="w-3.5 h-3.5 text-white" />
                          </div>
                        </motion.div>
                      )}

                      {/* Voice Info */}
                      <div className="p-4 space-y-2">
                        <div className="flex items-center gap-2.5">
                          <div className={cn(
                            "w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 text-lg",
                            "bg-gradient-to-br",
                            isSelected 
                              ? "from-purple-500/30 to-pink-500/30" 
                              : "from-purple-500/10 to-pink-500/10"
                          )}>
                            {voice.gender === 'male' ? '👨' : '👩'}
                          </div>
                          <div className="flex-1 min-w-0">
                            <h4 className={cn(
                              "font-semibold text-sm mb-0.5 truncate",
                              isSelected ? "text-white" : "text-white/90"
                            )}>
                              {voice.name}
                            </h4>
                            <p className="text-xs text-white/50 line-clamp-1 capitalize">
                              {voice.age === 'middle-aged' ? 'Middle-aged' : voice.age}
                            </p>
                          </div>
                        </div>
                      </div>

                      {/* Preview Button */}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          playPreview(voice.id, voice.previewUrl, e);
                        }}
                        className={cn(
                          "w-full py-2 px-3 transition-all",
                          "flex items-center justify-center gap-1.5",
                          "border-t border-white/5",
                          "text-xs font-medium",
                          isPlaying
                            ? "bg-gradient-to-r from-purple-500/80 to-pink-500/80 text-white"
                            : "bg-white/[0.02] hover:bg-white/5 text-white/50 hover:text-white/70"
                        )}
                      >
                        {isPlaying ? (
                          <>
                            <Pause className="w-3 h-3" />
                            <span>Playing</span>
                          </>
                        ) : (
                          <>
                            <Play className="w-3 h-3" />
                            <span>Preview</span>
                          </>
                        )}
                      </button>
                    </motion.div>
                  );
                })}
              </AnimatePresence>
            </div>

            {/* Voiceover Summary - Compact */}
            <div className="flex items-center justify-between p-3 rounded-lg bg-white/[0.03] border border-white/5">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500/20 to-pink-500/20 flex items-center justify-center">
                  <AudioWaveform className="w-4 h-4 text-purple-400" />
                </div>
                <div>
                  <p className="text-xs text-white/40">Total Narration</p>
                  <p className="text-sm font-medium text-white">
                    {wordCount} words • ~{Math.ceil(wordCount / 150)} min
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-white/5">
                <Mic className="w-3.5 h-3.5 text-purple-400" />
                <span className="text-xs text-white/60">
                  {scenes.length} {scenes.length === 1 ? 'scene' : 'scenes'}
                </span>
              </div>
            </div>

            {/* Info Message - Auto generation notice */}
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="relative overflow-hidden rounded-lg border border-purple-500/20 bg-gradient-to-r from-purple-500/5 to-pink-500/5"
            >
              <div className="flex items-center gap-3 p-4">
                <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center flex-shrink-0">
                  <AudioWaveform className="w-4 h-4 text-purple-400" />
                </div>
                <div className="flex-1">
                  <p className="text-sm text-white/70">
                    <span className="text-purple-300 font-medium">🎙️ Voiceover auto-generated</span>
                    {' '}when you click "Continue to Export"
                  </p>
                </div>
              </div>
            </motion.div>
          </div>
        </GlassPanel>
      )}

      {/* Background Music Section - AI Generated */}
      <GlassPanel>
        <div className="space-y-6">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className={cn(
                "w-10 h-10 rounded-xl flex items-center justify-center",
                "bg-gradient-to-br from-blue-500/20 to-cyan-500/20"
              )}>
                <Music className="w-5 h-5 text-blue-400" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white">Background Music</h3>
                <p className="text-sm text-white/60">AI-generated music to enhance your video</p>
              </div>
            </div>
            {/* AI Badge */}
            <div className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-full bg-gradient-to-r from-blue-500/10 to-purple-500/10 border border-blue-500/20">
              <Sparkles className="w-3.5 h-3.5 text-blue-400" />
              <span className="text-xs font-medium text-blue-300">AI Powered</span>
            </div>
          </div>

          {/* Music Style Grid - 4 columns on large, 2 on small */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            {MUSIC_STYLES.map((style, index) => {
              const isSelected = musicStyle === style.id;

              return (
                <motion.button
                  key={style.id}
                  onClick={() => onMusicStyleChange(style.id)}
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: index * 0.03 }}
                  className={cn(
                    "relative p-3 rounded-xl transition-all text-left overflow-hidden",
                    "border backdrop-blur-sm",
                    isSelected
                      ? `border-blue-500/50 bg-gradient-to-br ${style.gradient} shadow-lg shadow-blue-500/10`
                      : "border-white/10 bg-white/[0.03] hover:border-blue-500/30 hover:bg-white/[0.06]"
                  )}
                >
                  {/* Selected Indicator */}
                  {isSelected && (
                    <motion.div 
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      className="absolute top-2 right-2 z-10"
                    >
                      <div className="w-5 h-5 rounded-full bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center">
                        <Check className="w-3 h-3 text-white" />
                      </div>
                    </motion.div>
                  )}

                  <div className="flex items-center gap-2.5">
                    <div className={cn(
                      "w-9 h-9 rounded-lg flex items-center justify-center text-xl",
                      "bg-gradient-to-br",
                      style.gradient
                    )}>
                      {style.icon}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium text-sm text-white truncate">{style.name}</div>
                      <div className="text-xs text-white/50 truncate">{style.desc}</div>
                    </div>
                  </div>
                </motion.button>
              );
            })}
          </div>

          {/* Custom Music Upload Section */}
          <div className="pt-4 border-t border-white/10">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Upload className="w-4 h-4 text-purple-400" />
                <span className="text-sm font-medium text-white">Or Upload Your Own</span>
              </div>
              {customMusicUrl && (
                <span className="text-xs text-green-400 font-medium">Active</span>
              )}
            </div>

            {customMusicUrl ? (
              // Show uploaded music preview
              <div className="relative group">
                <div className={cn(
                  "rounded-xl border border-purple-500/30 bg-gradient-to-br from-purple-500/10 to-pink-500/10 p-4",
                  "backdrop-blur-sm"
                )}>
                  {/* Audio Element (hidden) */}
                  <audio 
                    ref={musicPreviewRef}
                    src={customMusicUrl}
                    onEnded={handleMusicEnded}
                    preload="metadata"
                  />
                  
                  <div className="flex items-center gap-4">
                    {/* Play/Pause Button */}
                    <button
                      onClick={toggleMusicPreview}
                      className={cn(
                        "w-12 h-12 rounded-full flex items-center justify-center transition-all",
                        "bg-gradient-to-br from-purple-500 to-pink-500",
                        "hover:from-purple-400 hover:to-pink-400",
                        "shadow-lg shadow-purple-500/25"
                      )}
                    >
                      {isMusicPlaying ? (
                        <Pause className="w-5 h-5 text-white" />
                      ) : (
                        <Play className="w-5 h-5 text-white ml-0.5" />
                      )}
                    </button>
                    
                    {/* Music Info */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <Volume2 className="w-4 h-4 text-purple-400 flex-shrink-0" />
                        <p className="text-sm text-white font-medium truncate">Custom Music</p>
                      </div>
                      <p className="text-xs text-white/50 mt-0.5">
                        Duration: {formatDuration(customMusicDuration)}
                        {customMusicDuration > 0 && customMusicDuration < duration && (
                          <span className="text-amber-400 ml-2">
                            (shorter than video)
                          </span>
                        )}
                      </p>
                    </div>
                    
                    {/* Visual Indicator */}
                    {isMusicPlaying && (
                      <div className="flex items-center gap-0.5">
                        {[1, 2, 3, 4].map((i) => (
                          <motion.div
                            key={i}
                            className="w-1 bg-gradient-to-t from-purple-500 to-pink-400 rounded-full"
                            animate={{
                              height: [8, 16, 8],
                            }}
                            transition={{
                              duration: 0.5,
                              repeat: Infinity,
                              delay: i * 0.1,
                            }}
                          />
                        ))}
                      </div>
                    )}
                  </div>
                </div>
                
                {/* Remove Button */}
                <button
                  onClick={handleRemoveCustomMusic}
                  className="absolute -top-2 -right-2 p-1.5 rounded-full bg-red-500/90 hover:bg-red-500 text-white shadow-lg transition-all opacity-0 group-hover:opacity-100"
                  title="Remove custom music"
                >
                  <X className="w-3 h-3" />
                </button>
              </div>
            ) : (
              // Upload area
              <div 
                className={cn(
                  "relative border-2 border-dashed rounded-xl p-5 text-center transition-all cursor-pointer",
                  isUploadingMusic 
                    ? "border-purple-400/50 bg-purple-500/10" 
                    : "border-white/10 hover:border-purple-400/30 hover:bg-purple-500/5"
                )}
                onClick={() => !isUploadingMusic && musicInputRef.current?.click()}
              >
                <input
                  ref={musicInputRef}
                  type="file"
                  accept="audio/*,.mp3,.wav,.m4a,.ogg"
                  className="hidden"
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) handleMusicUpload(file);
                  }}
                  disabled={isUploadingMusic}
                />
                
                {isUploadingMusic ? (
                  <div className="flex flex-col items-center gap-2">
                    <RefreshCw className="w-8 h-8 text-purple-400 animate-spin" />
                    <span className="text-sm text-white/60">Uploading music...</span>
                  </div>
                ) : (
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-purple-500/20 to-pink-500/20 flex items-center justify-center flex-shrink-0">
                      <Music className="w-6 h-6 text-purple-400" />
                    </div>
                    <div className="text-left">
                      <p className="text-sm text-white/80 font-medium">Upload custom music</p>
                      <p className="text-xs text-white/40 mt-0.5">MP3, WAV, M4A, OGG • Max 5 min</p>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Info note */}
            <p className="text-xs text-white/40 mt-3 text-center">
              {customMusicUrl 
                ? "✓ Custom music will be used. Music will be trimmed to match video length."
                : musicStyle !== 'none' 
                  ? "Custom music takes priority over AI-generated music"
                  : "Upload your own music or select an AI style above"
              }
            </p>
          </div>

          {/* AI Music Info Message */}
          {musicStyle !== 'none' && !customMusicUrl && (
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="relative overflow-hidden rounded-lg border border-blue-500/20 bg-gradient-to-r from-blue-500/5 to-purple-500/5"
            >
              <div className="flex items-center gap-3 p-3">
                <div className="w-8 h-8 rounded-lg bg-blue-500/20 flex items-center justify-center flex-shrink-0">
                  <Sparkles className="w-4 h-4 text-blue-400" />
                </div>
                <div className="flex-1">
                  <p className="text-sm text-white/70">
                    <span className="text-blue-300 font-medium">AI music will be generated</span>
                    {' '}during export to match your video duration
                  </p>
                </div>
              </div>
            </motion.div>
          )}

          {/* Volume Controls - Now in Export Step for real-time adjustment */}
          {voiceoverEnabled && musicStyle !== 'none' && (
            <div className="pt-4 border-t border-white/10">
              <div className="flex items-center gap-2 p-3 rounded-lg bg-blue-500/10 border border-blue-500/20">
                <Volume2 className="w-4 h-4 text-blue-400 flex-shrink-0" />
                <p className="text-xs text-white/70">
                  <span className="text-blue-300 font-medium">Volume controls</span>
                  {' '}will be available in the Export step for real-time adjustment
                </p>
              </div>
            </div>
          )}
        </div>
      </GlassPanel>
    </div>
  );
}
