import type { Character } from '@shared/schema';

/**
 * Step 2: World & Cast Data
 * Contains all settings and data from the World & Cast step
 */
export interface Step2Data {
  // AI Model Settings
  imageModel: string;  // e.g., "Flux", "Midjourney", "Nano Banana", "GPT Image"
  
  // Visual Style Settings
  artStyle: string;  // e.g., "none", "cinematic", "vintage", etc.
  styleReference?: string[];  // Array of reference image URLs (when artStyle is "none")
  cinematicInspiration?: string;  // Text description for cinematic inspiration
  
  // World Description
  worldDescription: string;
  
  // Custom Instructions
  imageInstructions: string;  // Image generation instructions
  videoInstructions: string;  // Video/animation instructions
  
  // Characters & Locations
  characters: Character[];  // Full character objects with all fields
  locations: Array<{
    id: string;
    name: string;
    description: string;
    details?: string;
    imageUrl?: string | null;
  }>;  // Full location objects
}

/**
 * Step 3: Scene Breakdown Data
 * Contains scenes and shots generated by Agent 3.1 and 3.2
 */
export interface Step3Data {
  scenes: Array<{
    id: string;
    videoId: string;
    sceneNumber: number;
    title: string;
    description?: string | null;
    duration?: number | null;
    videoModel?: string | null;
    imageModel?: string | null;
    cameraMotion?: string | null;
    lighting?: string | null;
    weather?: string | null;
    createdAt: Date | string;
  }>;
  shots: Record<string, Array<{
    id: string;
    sceneId: string;
    shotNumber: number;
    shotType: string;
    cameraMovement: string;
    duration: number;
    description?: string | null;  // Contains actionDescription only (visual action, no narration)
    videoModel?: string | null;
    imageModel?: string | null;
    soundEffects?: string | null;
    transition?: string | null;
    currentVersionId?: string | null;
    frameMode?: "image-reference" | "start-end"; // Per-shot mode (only used when narrativeMode === "auto")
    createdAt: Date | string;
    updatedAt: Date | string;
  }>>;
  shotVersions?: Record<string, any[]>;
  continuityLocked: boolean;
  continuityGroups: Record<string, any[]>;
}

/**
 * Agent 3.2: Shot Composer Input/Output Types
 */
export interface ShotComposerInput {
  script: string;
  scene: {
    id: string;
    sceneNumber: number;
    title: string;
    description?: string | null;
    duration?: number | null;
  };
  previousScenes: Array<{
    scene: {
      id: string;
      sceneNumber: number;
      title: string;
      description?: string | null;
      duration?: number | null;
    };
    shots: Array<{
      id: string;
      sceneId: string;
      shotNumber: number;
      shotType: string;
      cameraMovement: string;
      duration: number;
      description?: string | null;
      frameMode?: "image-reference" | "start-end";
    }>;
  }>;
  shotsPerScene: number | 'auto';
  characters: Array<{ id: string; name: string; description?: string }>;
  locations: Array<{ id: string; name: string; description?: string }>;
  genre: string;
  tone?: string;
  model?: string;
  availableDurations?: number[];  // Available video model durations (e.g., [2, 4, 5, 6, 8, 10, 12])
  narrativeMode?: "image-reference" | "start-end" | "auto";  // Global narrative mode
}

export interface ShotComposerOutput {
  shots: Array<{
    id: string;
    sceneId: string;
    shotNumber: number;
    shotType: string;
    cameraMovement: string;
    duration: number;
    description?: string | null;
    videoModel?: string | null;
    imageModel?: string | null;
    soundEffects?: string | null;
    transition?: string | null;
    currentVersionId?: string | null;
    frameMode?: "image-reference" | "start-end"; // Per-shot mode (only used when narrativeMode === "auto")
    createdAt: Date;
    updatedAt: Date;
  }>;
  continuityGroups?: Array<{
    id: string;
    sceneId: string;
    groupNumber: number;
    shotIds: string[];
    description?: string | null;
    transitionType?: string | null;
    status: string;
    editedBy?: string | null;
    editedAt?: Date | null;
    approvedAt?: Date | null;
    createdAt: Date;
  }>;
  cost?: number;
}

